# Generated by Django 2.2.2 on 2019-07-23 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pid', models.IntegerField()),
                ('path', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsname', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=50)),
                ('color', models.CharField(default='', max_length=50)),
                ('sizes', models.CharField(default='', max_length=50)),
                ('price', models.FloatField()),
                ('goodsnum', models.IntegerField()),
                ('pic_url', models.CharField(max_length=255)),
                ('goodsinfo', models.TextField(null=True)),
                ('ordernum', models.IntegerField(default=0)),
                ('clicknum', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('cateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Cates')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=255)),
                ('totalprice', models.FloatField()),
                ('status', models.IntegerField(default=0)),
                ('paytype', models.IntegerField(default=0)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('paytime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nikename', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0, null=True)),
                ('pic_url', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[(0, '女'), (1, '男')], max_length=1, null=True)),
                ('status', models.IntegerField(default=0)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('goodsid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Goods')),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Users'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='', max_length=20)),
                ('sizes', models.CharField(default='', max_length=20)),
                ('num', models.IntegerField()),
                ('lengths', models.IntegerField(default=1)),
                ('goodsid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Goods')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Users')),
            ],
        ),
    ]
