# Generated by Django 2.2.2 on 2019-07-26 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pid', models.IntegerField()),
                ('path', models.CharField(max_length=50)),
            ],
            options={
                'permissions': (('show_Cates', '查看分类列表权限'), ('create_Cates', '添加分类信息权限'), ('edit_Cates', '修改分类信息权限'), ('remove_Cates', '删除分类信息权限')),
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsname', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=50)),
                ('color', models.CharField(default='', max_length=50)),
                ('sizes', models.CharField(default='', max_length=50)),
                ('price', models.FloatField()),
                ('goodsnum', models.IntegerField()),
                ('pic_url', models.CharField(max_length=255)),
                ('goodsinfo', models.TextField(null=True)),
                ('ordernum', models.IntegerField(default=0)),
                ('clicknum', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('cateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Cates')),
            ],
            options={
                'permissions': (('show_Goods', '查看商品列表权限'), ('create_Goods', '添加商品信息权限'), ('edit_Goods', '修改商品信息权限'), ('remove_Goods', '删除商品信息权限')),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=255)),
                ('totalprice', models.FloatField()),
                ('status', models.IntegerField(default=0)),
                ('paytype', models.IntegerField(default=0)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('paytime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nikename', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0, null=True)),
                ('pic_url', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[(1, '男'), (0, '女')], max_length=1, null=True)),
                ('status', models.IntegerField(default=0)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'permissions': (('show_Uswrs', '查看用户列表权限'), ('create_Users', '添加用户信息权限'), ('edit_Users', '修改用户信息权限'), ('remove_Users', '删除用户信息权限')),
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('price', models.FloatField()),
                ('goodsid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Goods')),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Order')),
            ],
            options={
                'permissions': (('show_Order', '查看订单列表权限'), ('create_Order', '添加订单信息权限'), ('edit_Order', '修改订单信息权限'), ('remove_Order', '删除订单信息权限')),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Users'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='', max_length=20)),
                ('sizes', models.CharField(default='', max_length=20)),
                ('num', models.IntegerField()),
                ('lengths', models.IntegerField(default=1)),
                ('goodsid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Goods')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Users')),
            ],
        ),
    ]
