# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-17 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_auto_20190708_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='brand',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
